name: dotnet-format
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  check-format:
    runs-on: windows-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: '5.0.x'

      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format

      - name: Check out code
        uses: actions/checkout@v2.4.2

      - name: Run dotnet-format
        run: dotnet format '.\' --folder --check --verbosity diagnostic
